#! /bin/bash -ex
cd /root
cloud=`cat /etc/rightscale.d/cloud`

case $cloud in
softlayer)
  if [ ! -d /root/ruby-1.9.3-p194 ]; then
    yum erase ruby ruby-libs ruby-mode ruby-rdoc ruby-irb ruby-ri ruby-docs
    yum install openssl-devel zlib-devel gcc gcc-c++ make autoconf readline-devel curl-devel expat-devel gettext-devel libyaml
    wget http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p194.tar.gz
    tar zxf ruby-1.9.3-p194.tar.gz
    cd ruby-1.9.3-p194
    ./configure --enable-shared --enable-pthread --prefix=/usr
    make; make install
  fi
  ;;
esac

gem install google_drive --no-rdoc --no-ri

# format and mount disk
ls -C /dev
case $cloud in

ec2)
  if [ -e /dev/xvdq ]; then
    if ! mount | egrep '/dev/xvdq'; then
      mkdir -p /mnt/ebs
      mkfs.ext4 -F -q /dev/xvdq
      mount /dev/xvdq /mnt/ebs
    fi
  fi
  ;;

google)
  # If we're a donor instance (without attached disk), then kill rightlink
  if [ ! -e /dev/vdc ]; then
    ps -ax
    echo "*** Here we go... ***"
    pkill -9 collectd; pkill -9 monit; pkill -9 ruby
    ps -ax
    exit 1
  fi

  if [ -e /dev/vdb ]; then
    if ! mount | egrep '/dev/vdb'; then
      mkfs.ext4 -F -q /dev/vdb
      mount /dev/vdb /mnt/ephemeral
    fi
  fi
  if [ -e /dev/vdc ]; then
    if ! mount | egrep '/dev/vdc'; then
      mkfs.ext4 -F -q /dev/vdc
      mkdir -p /mnt/ebs
      mount /dev/vdc /mnt/ebs
    fi
  fi
  ;;

azure)
  if [ -d /mnt/resource ]; then
    umount /mnt/resource
    rmdir /mnt/resource
    mkdir -p /mnt/ephemeral
    mount /dev/sdb1 /mnt/ephemeral
  fi
  ;;

softlayer)
  if [ -e /dev/xvdc ]; then
    if ! mount | egrep xvdc; then
      yum install e4fsprogs.x86_64 -y
      /sbin/mkfs.ext4 -F -q /dev/xvdc
      mkdir -p /mnt/ephemeral
      mount /dev/xvdc /mnt/ephemeral
    fi
  fi
  ;;

rackspace)
  if [ -e /dev/xvda ]; then
    if ! mount | egrep xvda2; then
      yum install e4fsprogs.x86_64 -y
      /sbin/parted -s /dev/xvda mkpart primary 10200547328B 81604378622B
      sleep 5 # the new dev may take a few secs to appear?
      /sbin/mkfs.ext4 -F -q /dev/xvda2
      mount /dev/xvda2 /mnt/ephemeral

      wget http://www.coker.com.au/bonnie++/experimental/bonnie++-1.96.tgz
      tar zxf bonnie++-1.96.tgz
      cd bonnie++-1.96
      ./configure --prefix=/usr
      make install
    fi
  fi

esac

df -h
