#! /bin/bash -ex
cd /root
cloud=`cat /etc/rightscale.d/cloud`

gem install google_drive --no-rdoc --no-ri

# format and mount disk
ls -C /dev
case $cloud in

ec2)
  if [ -e /dev/xvdq ]; then
    if ! mount | egrep '/dev/xvdq'; then
      mkdir -p /mnt/ebs
      mkfs.ext4 -F -q /dev/xvdq
      mount /dev/xvdq /mnt/ebs
    fi
  fi
  ;;

google)
  if [ -e /dev/vdb ]; then
    if ! mount | egrep '/dev/vdb'; then
      mkfs.ext4 -F -q /dev/vdb
      mount /dev/vdb /mnt/ephemeral
    fi
  fi
  ;;

rackspace)
  if [ -e /dev/xvda ]; then
    if ! mount | egrep xvda2; then
      yum install e4fsprogs.x86_64 -y
      /sbin/parted -s /dev/xvda mkpart primary 10200547328B 81604378622B
      /sbin/mkfs.ext4 -F -q /dev/xvda2
      mount /dev/xvda2 /mnt/ephemeral

      wget http://www.coker.com.au/bonnie++/experimental/bonnie++-1.96.tgz
      tar zxf bonnie++-1.96.tgz
      cd bonnie++-1.96
      ./configure --prefix=/usr
      make install
    fi
  fi

esac

df -h
