#! /usr/bin/env ruby
require 'rubygems'
require 'google_drive'

GS='0Aq-daXyC3OSSdFhqY1lORFdHSkdZMjJraTBKa0thQUE'
#$gs = GoogleDrive.saved_session
$gs = GoogleDrive::Session.new({:wise => open('.ssh_tok').gets.chomp}, nil)
$ss = $gs.spreadsheet_by_key(GS)
ws = "raw " + Time.now.strftime("%Y-%m")
puts "Spreadsheet: #{$ss.title} / #{ws}"
$sheet = $ss.worksheet_by_title(ws)
$sheet ||= $ss.add_worksheet(ws)

def append_row(gs_session, gs_sheet, row_hash={})
  xml = '<entry xmlns="http://www.w3.org/2005/Atom" xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended">'
  row_hash.each_pair do |k, v|
    xml << "<gsx:#{k}>#{v}</gsx:#{k}>"
  end
  xml << "</entry>"
  gs_session.request(:post, gs_sheet.list_feed_url, :data => xml)
end

info=ARGV
#puts info.join(' ')
t={}
v=nil
while line = STDIN.gets
  puts line.chomp
  if line =~ /Version\s*([\d.]+)/
    v = $1
  elsif line =~ /\d+,\d+,\d+,/
    t = line.split(',')
  end
end

if v == '1.03'
  t[0] = info[1]
  t.unshift info[0]
else
  t.shift
  t[0] = info[0]
  t[1] = info[1]
end

cols = %w{cloud machine size seqwr-chr-kbs seqwr-chr-cpu seqwr-blk-kbs  seqwr-blk-cpu rewr-blk-kbs rewr-blk-cpu  seqrd-chr-kbs  seqrd-chr-cpu seqrd-blk-kbs  seqrd-blk-cpu rndseek-rate  rndseek-cpu}

data = {}
t.each_index do |i|
  data[cols[i]||i] = t[i]
end
append_row($gs, $sheet, data)

exit


=begin
cols = if v == '1.03'
    { :seqrd => 10, :seqwr => 4, :rndseek => 12 }
  else
    { :seqrd => 15, :seqwr => 9, :rndseek => 17 }
  end
cols.each_pair do |test, ix|
  next unless t[ix]
  puts "#{info.join(' ')}-#{test.to_s} #{t[ix]}"

  r = $sheet.num_rows
  $sheet[r+1,1] = info[0]
  $sheet[r+1,2] = info[1]
  $sheet[r+1,3] = info[2] + "-" + test.to_s
  $sheet[r+1,4] = t[ix]
end

$sheet.save
=end

#Version  1.03       ------Sequential Output------ --Sequential Input- --Random-
#                    -Per Chr- --Block-- -Rewrite- -Per Chr- --Block-- --Seeks--
#Machine        Size K/sec %CP K/sec %CP K/sec %CP K/sec %CP K/sec %CP  /sec %CP
#ip-10-252-13 35000M 78668  97 89875   5 37182   0 65976  70 114628   0 314.2   0
#                    ------Sequential Create------ --------Random Create--------
#                    -Create-- --Read--- -Delete-- -Create-- --Read--- -Delete--
#              files  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP
#                 16 12019  22 +++++ +++  6829   5 10581  20 +++++ +++  4891   1
#ip-10-252-134-197,35000M,78668,97,89875,5,37182,0,65976,70,114628,0,314.2,0,16,12019,22,+++++,+++,6829,5,10581,20,+++++,+++,4891,1
#
