#! /usr/bin/env ruby
require File.dirname(__FILE__) + '/gs.rb'
gs_init('fio')

info=ARGV
#puts info.join(' ')
t=[]
v=nil
while line = STDIN.gets
  puts line.chomp
end

exit 0

if v == '1.96'
  t[0] = info[0]
  t[1] = info[1]
  t[2] = info[0] + '-' + info[1]
  t[4] = Time.now.strftime("%Y/%m/%d %H:%M") # Time.at(t[3].to_i).strftime("%Y/%m/%d %H:%M")
end

cols = %w{name options label concurrency time size files
    seqwr-chr-kbs seqwr-chr-cpu seqwr-blk-kbs seqwr-blk-cpu rewr-blk-kbs rewr-blk-cpu
    seqrd-chr-kbs seqrd-chr-cpu seqrd-blk-kbs seqrd-blk-cpu rndseek-rate rndseek-cpu}

data = {}
t.each_index do |i|
  data[cols[i]||i] = t[i]
end
append_row($gs, $sheet, data)

=begin
prep: (g=0): rw=write, bs=4K-4K/4K-4K, ioengine=sync, iodepth=1
2.0.8
Starting 1 process
prep: Laying out IO file(s) (1 file(s) / 30720MB)
Jobs: 1 (f=1): [W] [99.6% done] [0K/140.5M /s] [0 /35.1K iops] [eta 00m:01s]
prep: (groupid=0, jobs=1): err= 0: pid=10395
  write: io=30720MB, bw=131049KB/s, iops=32762 , runt=240042msec
    clat (usec): min=2 , max=724891 , avg=26.57, stdev=1196.43
     lat (usec): min=2 , max=724892 , avg=27.26, stdev=1199.81
    clat percentiles (usec):
     |  1.00th=[    3],  5.00th=[    3], 10.00th=[    3], 20.00th=[    5],
     | 30.00th=[    6], 40.00th=[    6], 50.00th=[    7], 60.00th=[    7],
     | 70.00th=[    7], 80.00th=[    7], 90.00th=[    8], 95.00th=[    9],
     | 99.00th=[   18], 99.50th=[   24], 99.90th=[ 3120], 99.95th=[ 9920],
     | 99.99th=[38144]
    bw (KB/s)  : min=    6, max=926712, per=100.00%, avg=133673.48, stdev=114513.92
    lat (usec) : 4=10.84%, 10=84.73%, 20=3.79%, 50=0.32%, 100=0.02%
    lat (usec) : 250=0.10%, 500=0.04%, 750=0.01%, 1000=0.01%
    lat (msec) : 2=0.02%, 4=0.03%, 10=0.04%, 20=0.02%, 50=0.02%
    lat (msec) : 100=0.01%, 250=0.01%, 500=0.01%, 750=0.01%
  cpu          : usr=9.75%, sys=65.45%, ctx=6001, majf=0, minf=27
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=7864320/d=0, short=r=0/w=0/d=0

Run status group 0 (all jobs):
  WRITE: io=30720MB, aggrb=131049KB/s, minb=131049KB/s, maxb=131049KB/s, mint=240042msec, maxt=240042msec

Disk stats (read/write):
  vdb: ios=0/60884, merge=0/57417, ticks=0/31834060, in_queue=31873380, util=98.43%
