#! /usr/bin/env ruby
require 'rubygems'
require 'google_drive'

GS='0Aq-daXyC3OSSdFhqY1lORFdHSkdZMjJraTBKa0thQUE'
#$gs = GoogleDrive.saved_session
$gs = GoogleDrive::Session.new({:wise => open('.ssh_tok').gets.chomp}, nil)
$ss = $gs.spreadsheet_by_key(GS)
ws = "raw " + Time.now.strftime("%Y-%m")
puts "Spreadsheet: #{$ss.title} / #{ws}"
$sheet = $ss.worksheet_by_title(ws)
$sheet ||= $ss.add_worksheet(ws)

info=ARGV
#puts info.join(' ')
v = nil
cpu = false
while line = STDIN.gets
  puts line.chomp
  if line =~ /transferred.*\(([\d.]+)\s*(\w?)[bB]\/sec/
    v = $1.to_f; u = $2
    case u
    when 'G' then v *= 1000000
    when 'M' then v *= 1000
    when 'K' then v
    when ''  then v *= 0.001
    else
      puts "unknown unit #{u}!"
      v = nil
    end
  elsif line =~ /prime number/
    cpu = true
  elsif cpu && line =~ /avg:\s+([\d.]+)ms/
    v = $1
  end
end
puts "#{info.join(' ')} #{v}"

exit unless v

r = $sheet.num_rows
$sheet[r+1,1] = info[0]
$sheet[r+1,2] = info[1]
$sheet[r+1,3] = info[2]
$sheet[r+1,4] = v

$sheet.save
