#! /usr/bin/env ruby
require 'rubygems'
require 'google_drive'

GS='0Aq-daXyC3OSSdFhqY1lORFdHSkdZMjJraTBKa0thQUE'
#$gs = GoogleDrive.saved_session
$gs = GoogleDrive::Session.new({:wise => open('.ssh_tok').gets.chomp}, nil)
$ss = $gs.spreadsheet_by_key(GS)
ws = "bonnie " + Time.now.strftime("%Y-%m")
puts "Spreadsheet: #{$ss.title} / #{ws}"
$sheet = $ss.worksheet_by_title(ws)
$sheet ||= $ss.add_worksheet(ws)

def append_row(gs_session, gs_sheet, row_hash={})
  xml = '<entry xmlns="http://www.w3.org/2005/Atom" xmlns:gsx="http://schemas.google.com/spreadsheets/2006/extended">'
  row_hash.each_pair do |k, v|
    xml << "<gsx:#{k}>#{v}</gsx:#{k}>"
  end
  xml << "</entry>"
  gs_session.request(:post, gs_sheet.list_feed_url, :data => xml)
end

info=ARGV
#puts info.join(' ')
t=[]
v=nil
while line = STDIN.gets
  puts line.chomp
  if line =~ /Version\s*([\d.]+)/
    v = $1
  elsif line =~ /\d+,\d+,\d+,/
    t = line.split(',')
  end
end

if v == '1.96'
  t.shift
  t[0] = info[0]
  t[1] = info[1]
  t[3] = Time.at(t[3].to_i).strftime("%Y/%m/%d %H:%M")
end

cols = %w{machine options concurrency time size files
    seqwr-chr-kbs seqwr-chr-cpu seqwr-blk-kbs seqwr-blk-cpu rewr-blk-kbs rewr-blk-cpu
    seqrd-chr-kbs seqrd-chr-cpu seqrd-blk-kbs seqrd-blk-cpu rndseek-rate rndseek-cpu}

data = {}
t.each_index do |i|
  data[cols[i]||i] = t[i]
end
append_row($gs, $sheet, data)

=begin
Version  1.96       ------Sequential Output------ --Sequential Input- --Random-
Concurrency   1     -Per Chr- --Block-- -Rewrite- -Per Chr- --Block-- --Seeks--
Machine        Size K/sec %CP K/sec %CP K/sec %CP K/sec %CP K/sec %CP  /sec %CP
ip-10-248-77- 3520M   528  99 94651  11 54413  10   758  99 139210  13 267.2   3
Latency             16896us    1644ms     167ms   18877us   58241us    2083ms

1.96,1.96,ip-10-248-77-246,1,1340479107,3520M,,528,99,94651,11,54413,10,758,99,139210,13,267.2,3,,,,,,,,,,,,,,,,,,16896us,1644ms,167ms,18877us,58241us,2083ms,,,,,,
=end

#Version  1.03       ------Sequential Output------ --Sequential Input- --Random-
#                    -Per Chr- --Block-- -Rewrite- -Per Chr- --Block-- --Seeks--
#Machine        Size K/sec %CP K/sec %CP K/sec %CP K/sec %CP K/sec %CP  /sec %CP
#ip-10-252-13 35000M 78668  97 89875   5 37182   0 65976  70 114628   0 314.2   0
#                    ------Sequential Create------ --------Random Create--------
#                    -Create-- --Read--- -Delete-- -Create-- --Read--- -Delete--
#              files  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP
#                 16 12019  22 +++++ +++  6829   5 10581  20 +++++ +++  4891   1
#ip-10-252-134-197,35000M,78668,97,89875,5,37182,0,65976,70,114628,0,314.2,0,16,12019,22,+++++,+++,6829,5,10581,20,+++++,+++,4891,1
#
