#! /bin/bash
set -x
PATH=$PATH:/root/cloudbench

df -h
ls -ls /mnt

cd /root
gb_mem=`ruby -n -e '$_ =~ /MemTotal/ && puts($_.split[1].to_i/1024/1024)' /proc/meminfo`
sz=
if [ $gb_mem -lt 20 ]; then
  sz="40G"
else
  sz=`expr $gb_mem \* 2`G
fi
#sz=1G

ini=/root/cloudbench/fio.ini

echo '===== creating files ============================================='

# create all the files
for d in ebs ebs2 ephemeral; do
  if [ -d /mnt/$d ]; then
    mkdir -p /mnt/$d/fio
    cd /mnt/$d/fio/
    rm -f fio
    df -h .
    fio --name=prep --rw=write --size=$sz --filename=fio --bs=1M --ioengine=libaio --iodepth=16 --end_fsync=1 &
    sleep 10
  fi
done
wait

# run the benchmarks a few times
for i in 1 2 3; do
  echo "===== benchmark run $i == $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i ====="
  for d in ebs ebs2 ephemeral; do
    if [ -d /mnt/$d ]; then
      cd /mnt/$d/fio
      now=`date "+%Y/%m/%d %H:%M:%S"`
      label=$CLOUD-$MACHINE-$d
      fio $ini 2>&1 | tee /tmp/fio-$$
      link=`s3-log fio $label "$now" /tmp/fio-$$ | egrep 'http:'`
      report-fio $CLOUD-$MACHINE "$d" "$now" "$link" </tmp/fio-$$
    fi
  done
done
